FROM python:3.11.10-slim

WORKDIR /app

COPY requirements.txt requirements_production.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements_production.txt

# Copy the rest of your application code to the container
COPY src/ .

# vim: set ft=dockerfile:
