services:
  llmsearch:
    container_name: llmsearch-llmsearch
    image: llmsearch:latest
    ports:
      - "58000:58000"
    environment:
      - FLASK_APP=llmsearch
      - FLASK_ENV=development
      - FLASK_RUN_HOST=

  postgres:
    container_name: llmsearch-postgres
    # image: postgres:17.0-bookworm
    image: postgres-pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=llmsearchdb
    # networks:
    #   - llmsearch
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 55432:5432
    restart: always

  pgadmin:
    container_name: llmsearch-pgadmin
    image: dpage/pgadmin4:8.12
    environment:
      - PGADMIN_DEFAULT_EMAIL=nuffin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    # networks:
    #   - llmsearch
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 55050:80
    restart: always

  elasticsearch:
    container_name: llmsearch-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true # Enable security features
      - ELASTIC_PASSWORD=secret # Set the password for 'elastic' user
      - xpack.security.authc.api_key.enabled=true # Enable API key authentication (optional)
    ports:
      - "59200:9200"
      - "59300:9300"
    # networks:
    #   - llmsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data

  localai:
    container_name: llmsearch-localai
    image: localai/localai:latest-aio-gpu-nvidia-cuda-12
    ports:
      - "58080:8080"
    volumes:
      - local-ai-models:/build/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # networks:
    #   - llmsearch

  ollama:
    container_name: llmsearch-ollama
    image: ollama:latest
    ports:
      - "51400:51400"
    environment:
      - OLLAMA_HOST=0.0.0.0:51400
    volumes:
      - ollama-models:/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # networks:
    #   - llmsearch

  # opensearch-node1:
  #   container_name: llmsearch-opensearch-node1
  #   image: opensearchproject/opensearch:2.5.0 # You can choose the version you need
  #   environment:
  #     - cluster.name=opensearch-cluster
  #     - node.name=opensearch-node1
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "DISABLE_SECURITY_PLUGIN=true" # Enable security plugin
  #     - "OPENSEARCH_SECURITY_ADMIN_PASSWORD=secret" # Set admin password
  #     # - "OPENSEARCH_SECURITY_AUTO_USE_EXISTING_KEYSTORE=true"
  #     # - "OPENSEARCH_SECURITY_ALLOW_DEFAULT_SSL_CERTIFICATE=true" # To use self-signed certificates
  #     - "OPENSEARCH_SECURITY_SSL_HTTP_ENABLED=false" # Disable HTTP SSL
  #     - "OPENSEARCH_SECURITY_SSL_TRANSPORT_ENABLED=false" # Disable transport SSL
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - opensearch-data:/usr/share/opensearch/data
  #   ports:
  #     - "59200:9200" # OpenSearch REST API
  #     - "59600:9600" # Performance Analyzer
  #   # networks:
  #   #   - llmsearch
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9200"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  # opensearch-dashboards:
  #   container_name: llmsearch-opensearch-dashboards
  #   image: opensearchproject/opensearch-dashboards:2.5.0
  #   ports:
  #     - "55601:5601" # OpenSearch Dashboards
  #   environment:
  #     OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
  #     OPENSEARCH_SECURITY_ADMIN_PASSWORD: admin_password # Set the admin password here for dashboards
  #   # networks:
  #   #   - llmsearch

# networks:
#   llmsearch:
#     driver: bridge

volumes:
  pgdata:
  pgadmin-data:
  esdata:
    driver: local
  opensearch-data:
  local-ai-models:
  ollama-models:

