from env import getenv


class Config:
    DEBUG = True

    SERVER_NAME = getenv("SERVER_NAME")
    HOST = getenv("HOST")
    PORT = getenv("PORT")
    DATABASE_URI = getenv("DATABASE_URI")
    PUBLIC_PATH = getenv("PUBLIC_PATH")
    UPLOADS_PATH = getenv("UPLOADS_PATH")
    SQLALCHEMY_ENGINE_POOL_SIZE = getenv("SQLALCHEMY_ENGINE_POOL_SIZE")
    SQLALCHEMY_ENGINE_MAX_OVERFLOW = getenv("SQLALCHEMY_ENGINE_MAX_OVERFLOW")
    SQLALCHEMY_ENGINE_POOL_TIMEOUT = getenv("SQLALCHEMY_ENGINE_POOL_TIMEOUT")
    SQLALCHEMY_ENGINE_POOL_RECYCLE = getenv("SQLALCHEMY_ENGINE_POOL_RECYCLE")
    SQLALCHEMY_ENGINE_POOL_PRE_PING = getenv("SQLALCHEMY_ENGINE_POOL_PRE_PING")
    LOG_LEVEL = getenv("LOG_LEVEL")

    SQLALCHEMY_DATABASE_URI = DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ENGINE_OPTIONS = {
        "pool_size": SQLALCHEMY_ENGINE_POOL_SIZE,
        "max_overflow": SQLALCHEMY_ENGINE_MAX_OVERFLOW,
        "pool_timeout": SQLALCHEMY_ENGINE_POOL_TIMEOUT,
        "pool_recycle": SQLALCHEMY_ENGINE_POOL_RECYCLE,
        "pool_pre_ping": SQLALCHEMY_ENGINE_POOL_PRE_PING,
    }
